export const COLORS = {
  PRIMARY: '#289a8d',
  SECONDARY: '#289d8f',
  PRIMARY_DARK: '#289c8f',
  LIGHT_PRIMARY:'#D4EBE8',
  PLACEHOLDER: '#A6B9C7',
  DISABLED_GREY: '#f4f4f4',
  DARK_GREY: '#444',
  SILVER_GREY: '#dedede',
  MAC_GREY: '#e0e0e0',
  CREAMY_GREY: '#efefef',
  OFF_WHITE: '#EEEEEE',
  WHITE_GREY: '#ebebeb',
  METAL_GREY:'#ddd',
  ASH_GREY: '#bdbfbe',
  OFF_GREY: '#ececec',
  WHITE: '#fff',
  BLACK: '#000',
  WHITEBLACK: '#fff',
  YELLOW_LIGHT: '#dff08d',
  BLUE: '#1faadb',
  ACTIVETAB: '#228c80',
  INACTIVETAB: '#1f7c71',
  RGB: 'rgba(0,0,0,0.5)',
  DOCUMENTATION : '#3fb766',
  GIFTDELIVERY :'#047aad',
  INSTAPAY: '#64b7f9',
  LEGALSERVICES : '#ffc75f',
  PROPERTYMNGMT : '#a7782b',
  SPECIALREQUEST : '#fcb747',
  IMMIGRATION: '#ee3b43',
  LIGHTGREEN: 'rgba(0,0,0,0.1)',
  OLDGREEN : '#26C165',
  SNACKBAR_GREEN:"#E2F1E7",
  INSTASHOPBG :'#EDF4F3'
};

export const DARK_COLORS = {
  PRIMARY: '#289a8d',
  SECONDARY: '#289d8f',
  PLACEHOLDER: '#A6B9C7',
  DISABLED_GREY: '#f4f4f4',
  DARK_GREY: '#444',
  SILVER_GREY: '#dedede',
  MAC_GREY: '#e0e0e0',
  CREAMY_GREY: '#efefef',
  OFF_WHITE: '#EEEEEE',
  WHITE_GREY: '#ebebeb',
  METAL_GREY: '#ddd',
  ASH_GREY: '#bdbfbe',
  OFF_GREY: '#ececec',
  WHITE: '#fff',
  BLACK: '#000',
  WHITEBLACK: '#000',
  YELLOW_LIGHT: '#dff08d',
  BLUE: '#1faadb',
  ACTIVETAB: '#228c80',
  INACTIVETAB: '#1f7c71',
  DOCUMENTATION : '#3fb766',
  GIFTDELIVERY :'#047aad',
  INSTAPAY: '#64b7f9',
  LEGALSERVICES : '#ffc75f',
  PROPERTYMNGMT : '#a7782b',
  SPECIALREQUEST : '#fcb747',
  IMMIGRATION: '#ee3b43',
  LIGHTGREEN: 'rgba(0,0,0,0.1)',
  OLDGREEN : '#26C165',
  SNACKBAR_GREEN:"#E2F1E7"
};
