export default {
  Profile2:require('../assets/profile2.png'),
  errorIcon:require('../assets/error-icon.png'),
  notify: require('../assets/notifylight.png'),
  backarrow: require('../assets/backarrow.png'),
  circle: require('../assets/circle.png'),
  square: require('../assets/square.png'),
  scanqr: require('../assets/scanqr.png'),
  circleicon: require('../assets/circleicon.png'),
  menuicon: require('../assets/menuicon.png'),
  bellicon: require('../assets/bellicon.png'),
  option: require('../assets/option.png'),
  profile: require('../assets/profile.png'),
  icon: require('../assets/icon1.png'),
  language: require('../assets/Language.png'),
  password: require('../assets/Password.png'),
  location: require('../assets/Location.png'),
  notification: require('../assets/notification-simple.png'),
  notificationfocused: require('../assets/Notification.png'),
  messagefocused: require('../assets/Message.png'),
  message: require('../assets/message-simple.png'),
  home: require('../assets/Home-simple.png'),
  homefocused: require('../assets/Home.png'),
  about: require('../assets/About.png'),
  privacy: require('../assets/privacy.png'),
  work: require('../assets/work.png'),
  contact: require('../assets/contact.png'),
  admin: require('../assets/Admin.png'),
  homeiconfocus: require('../assets/homeiconfocus.png'),
  btn1: require('../assets/btn1.png'),
  btn2: require('../assets/btn2.png'),
  aboutuslogo: require('../assets/insta.png'),
  search: require('../assets/search.png'),
  cancel:require('../assets/cancel.png'),
  greenbackarrow: require('../assets/greenbackarrow.png'),
  hidepass: require('../assets/hidepass_ico.png'),
  showpass: require('../assets/viewpass_ico.png'),
  myprofile: require('../assets/myprofile.png'),
  passwordlightgreen: require('../assets/passwordlightgreen.png'),
  Phone: require('../assets/Phone.png'),
  City: require('../assets/City.png'),
  Country: require('../assets/Country.png'),
  emaillightgreen: require('../assets/emaillightgreen.png'),
  unchecklightgreen: require('../assets/unchecklightgreen.png'),
  backIcon: require('../assets/backIcon.png'),
  CircleCheck: require('../assets/CircleCheck.png'),
  SquareCheck: require('../assets/SquareCheck.png'),
  Textlightgreen: require('../assets/Textlightgreen.png'),
  Checkgreen: require('../assets/Checkgreen.png'),
  logouticon: require('../assets/logout.png'),
  email: require('../assets/Email-Icon.png'),
  instakin: require('../assets/instakin.png'),
  cancel: require('../assets/cancel.png'),
  searchicon: require('../assets/Search-icon.png'),
  instakinWhite:require('../assets/instakin-white.png'),
  formIcon:require('../assets/form.png'),
  linkIcon:require('../assets/link.png'),
  selectIcon:require('../assets/select.png'),
  attachment:require('../assets/attachment.png'),
  send:require('../assets/send.png'),
  info:require('../assets/info.png'),
  profilePic:require('../assets/Customer-profile-green.png'),
  headerplus:require('../assets/headerplus.png'),
  addnewfriend:require('../assets/addnewfriend.png'),
  frienddelete:require('../assets/frienddelete.png'),
  phoneLightGreen:require('../assets/User-light-green.png'),
  editfriend:require('../assets/editfriend.png'),
  generalProfilePic:require('../assets/general_profile.png'),
  notificationFill:require('../assets/notificationfilled.png'),
  notificationEmpty:require('../assets/notificationempty.png'),
  whitecross:require('../assets/whitecross.png'),
  whitetick:require('../assets/whitetick.png'),
  demo1:require('../assets/demo1.png'),
  demo2:require('../assets/demo2.png'),
  demo3:require('../assets/demo3.png'),
  demo4:require('../assets/demo4.png'),
  demo5:require('../assets/demo5.png'),
  cancelIcon:require('../assets/close.png'),
  discount:require('../assets/discount-voucher1.png'),
  buildings:require('../assets/buildings1.png'),
	filter:require('../assets/filter.png'),
	heart:require('../assets/Heart.png'),
  cancelIcon:require('../assets/close.png'),
	star:require('../assets/star.png'),
	bag:require('../assets/shopping-bag.png'),
  bell:require('../assets/bell.png'),

  headerback:require('../assets/headerback.png'),
  heartfilled:require('../assets/heartfilled.png'),
  heartunfilled:require('../assets/heartunfilled.png'),
  shoppingbag:require('../assets/shoppingbag.png'),
  headerhome:require('../assets/headerhome.png'),
  headerdelete:require('../assets/headerdelete.png'),
  comingsoon:require('../assets/comingsoon.png'),
  bannerbg:require('../assets/bannerbg.png'),
  referral:require('../assets/referral.png'),
  referralbg:require('../assets/referralbg.png'),
  shareupload:require('../assets/shareupload.png'),
  
  
  WeChat:require('../assets/WeChat.png'),
  Messenger:require('../assets/Messenger.png'),
  WhatsApp:require('../assets/WhatsApp.png'),
  Instagram:require('../assets/Instagram.png'),
  copy:require('../assets/copy.png'),
  money:require('../assets/money.png'),
  settings:require('../assets/settings.png'),
  translation:require('../assets/translation.png'),
  rating:require('../assets/rating.png'),
  notificationbell:require('../assets/notification-bell.png'),
  changepassword:require('../assets/changepassword.png'),
  referralbackground:require('../assets/referralbackground.png'),
  dots:require('../assets/dots.png'),
  instaWhite: require('../assets/instaW.png'),
  tooltipAngle : require('../assets/triangle.png'),
  additem : require('../assets/additem.png'),
  removeitem : require('../assets/removeitem.png'),
  overlay : require('../assets/overlay.png'),
  cartbag : require('../assets/cartbag.png'),
  lightDocument : require('../assets/Iconly-Light-Document.png'),
  deliveryDate : require('../assets/Delivery_date.png'),
  locationIcon : require('../assets/locationIcon.png'),
  editIcon : require('../assets/Iconly-Light-Edit.png'),
  emptyIcon : require('../assets/emptyIcon.png'),
  imageLoader : require('../assets/ImageLoader1.png')};
