// const splashLogo = require('./splashLogo.png')
// const foodLogo = require('./foodLogo.png')

export default {
  appLogo:require('../assets/appLogo.png'),
  launch_screen: require('../assets/launch_screen.png'),
  fullGreen:require('../assets/splash1.png'),
  SignIn: require('../assets/SignIn.png'),
  BannerBackground: require('../assets/BannerBackground.png'),
  // splashLogo: require('../assets/splashLogo.png'),
  logo: require('../assets/logo.png'),
  Edit: require('../assets/Edit.png'),
  foodLogo: require('../assets/foodLogo.png'),
  barcode: require('../assets/barcode.png'),
  dominopizza: require('../assets/dominopizza.png'),
  dominos: require('../assets/Dominos.png'),
  pizzahut: require('../assets/pizzahut.png'),
  hut: require('../assets/hut.png'),
  cicipizza: require('../assets/cicipizza.png'),
  view: require('../assets/view.png'),
  jimmy: require('../assets/jimmy.png'),
  level1: require('../assets/level1.png'),
  level2: require('../assets/level2.png'),
  level3: require('../assets/level3.png'),
  QRColor: require('../assets/QRColor.png'),
  mcdonald: require('../assets/mcdonald.png'),
  homeiconfocus: require('../assets/homeiconfocus.png'),
  homeicon: require('../assets/homeicon.png'),
  walletfocus: require('../assets/walletfocus.png'),
  walletblack: require('../assets/walletblack.png'),
  pointfocus: require('../assets/pointfocus.png'),
  coinblack: require('../assets/coinblack.png'),
  locationfocus: require('../assets/locationfocus.png'),
  locationblack: require('../assets/locationblack.png'),
  categoriesfocus: require('../assets/categoriesfocus.png'),
  offerblack: require('../assets/offerblack.png'),
  map: require('../assets/map.png'),
  burgerkingimage: require('../assets/burgerkingimage.png'),
  mcdonaldsimage: require('../assets/mcdonaldsimage.png'),
  starbucks: require('../assets/starbucks.png'),
  kfc: require('../assets/kfc.png'),
  Restaurant: require('../assets/Restaurant.png'),
  Clothes: require('../assets/Clothes.png'),
  Cosmetics: require('../assets/Cosmetics.png'),
  Electronics: require('../assets/Electronics.png'),
  Travel: require('../assets/Travel.png'),
  Other: require('../assets/Other.png'),

  splashLogo: require('../assets/splashLogo.png'),
  foodLogo: require('../assets/foodLogo.png'),
  shopingLogo: require('../assets/shopingLogo.png'),
  english: require('../assets/english.png'),
  arabic: require('../assets/arabic.png'),
  turkey: require('../assets/turkey.png'),
  Myprofileimage: require('../assets/Myprofileimage.png'),
  centerPoint: require('../assets/iconcenterpoint.png'),

  howItWorks1: require('../assets/howItWorks1.png'),
  howItWorks2: require('../assets/howItWorks2.png'),
  howItWorks3: require('../assets/howItWorks3.png'),
  uploadImg: require('../assets/uploadImg.png'),
  updateImage:require('../assets/updateVersion.png')
  // splashLogo,
  // foodLogo,
};
